
RUNNING 10 EPISODES

BEGINNING EPISODE: 1

S: (0, 1), A: north, S': (0, 2), R: 0.0

S: (0, 2), A: north, S': (0, 3), R: 0.0

S: (0, 3), A: east, S': (0, 3), R: 0.0

S: (0, 3), A: north, S': (0, 4), R: 0.0

S: (0, 4), A: north, S': (0, 4), R: 0.0

S: (0, 4), A: north, S': (0, 4), R: 0.0

S: (0, 4), A: north, S': (0, 4), R: 0.0

S: (0, 4), A: east, S': (1, 4), R: 0.0

S: (1, 4), A: north, S': (1, 4), R: 0.0

S: (1, 4), A: south, S': (1, 4), R: 0.0

S: (1, 4), A: north, S': (1, 4), R: 0.0

S: (1, 4), A: east, S': (2, 4), R: 0.0

S: (2, 4), A: north, S': (2, 4), R: 0.0

S: (2, 4), A: north, S': (2, 4), R: 0.0

S: (2, 4), A: west, S': (2, 4), R: 0.0

S: (2, 4), A: north, S': (2, 4), R: 0.0

S: (2, 4), A: north, S': (2, 4), R: 0.0

S: (2, 4), A: north, S': (2, 4), R: 0.0

Receive Positive (+1) human signal

Traceback (most recent call last):
  File "/Users/lguan/env-tensorflow-py2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/lguan/env-tensorflow-py2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/lguan/Documents/Study/Research/Summer 2018/Week3/BerkeleyGridWorld/experiment/expr_runner_terminal.py", line 28, in <module>
    run_expr()
  File "/Users/lguan/Documents/Study/Research/Summer 2018/Week3/BerkeleyGridWorld/experiment/expr_runner_terminal.py", line 24, in run_expr
    tamerGridWorld.run_episodes()
  File "BerkeleyGridWorld/gridworld.py", line 573, in run_episodes
    , pause_callback, i_episode, user_input_module=self.user_input_module)
  File "BerkeleyGridWorld/gridworld.py", line 473, in runEpisode
    agent.receiveHumanSignal(human_signal=1)
  File "BerkeleyGridWorld/qlearningAgents.py", line 182, in receiveHumanSignal
    action = experience['action']
KeyError: 'action'
